# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FindRoute
                                 A QGIS plugin
 Find the best route between points
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-20
        copyright            : (C) 2020 by Karolina Aksamit
        email                : karolina.aksamit.ak@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FindRoute class from file FindRoute.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .findRoute import FindRoute
    return FindRoute(iface)
